In [46]:
import numpy as np

class dot():
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def dot_xy(self):
        dot_out = []
        for xi in self.x:
            dot_out.append((xi.reshape(-1,1)*self.y).sum(axis=0))
        return np.array(dot_out)

In [47]:
a = np.arange(9).reshape(3,3)
b = np.arange(6).reshape(3,2)
print(a)
print(b)
dot_ob = dot(a,b)
dot_ob.dot_xy()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [2 3]
 [4 5]]


array([[10, 13],
       [28, 40],
       [46, 67]])